variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

test:
  stage: test
  script:
  - source /opt/rh/devtoolset-6/enable
  - pip3 install --user -r requirements.txt
  - pip3 install --user --upgrade ./stencilflow/dace
  - python3 test/testing.py
